/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'docking',
    path: '/docking',
    component: 'layout.base',
    meta: {
      title: '对接网关',
      i18nKey: 'route.docking',
      order: 3
    },
    children: [
      {
        name: 'docking_list',
        path: '/docking/list',
        component: 'view.docking_list',
        meta: {
          title: '对接网关列表',
          i18nKey: 'route.docking_list'
        }
      },
      {
        name: 'docking_number',
        path: '/docking/number',
        component: 'view.docking_number',
        meta: {
          title: '对接号码池管理',
          i18nKey: 'route.docking_number'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'landing',
    path: '/landing',
    component: 'layout.base',
    meta: {
      title: '落地网关',
      i18nKey: 'route.landing',
      order: 2
    },
    children: [
      {
        name: 'landing_list',
        path: '/landing/list',
        component: 'view.landing_list',
        meta: {
          title: 'landing_list',
          i18nKey: 'route.landing_list'
        }
      },
      {
        name: 'landing_number',
        path: '/landing/number',
        component: 'view.landing_number',
        meta: {
          title: '落地号码管理',
          i18nKey: 'route.landing_number'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'statistics',
    path: '/statistics',
    component: 'layout.base',
    meta: {
      title: '查询统计',
      i18nKey: 'route.statistics',
      order: 4
    },
    children: [
      {
        name: 'statistics_records',
        path: '/statistics/records',
        component: 'view.statistics_records',
        meta: {
          title: '话单查询',
          i18nKey: 'route.statistics_records'
        }
      }
    ]
  }
];
